export const flagMap: Record<string, string> = {
  Mexico: 'mx',
  'South Africa': 'za',
  'South Korea': 'kr',
  'Czech Republic': 'cz',
  Canada: 'ca',
  'Bosnia and Herzegovina': 'ba',
  'United States': 'us',
  Paraguay: 'py',
  Haiti: 'ht',
  Scotland: 'gb-sct',
  Australia: 'au',
  Turkey: 'tr',
  Brazil: 'br',
  Morocco: 'ma',
  Qatar: 'qa',
  Switzerland: 'ch',
  'Ivory Coast': 'ci',
  Ecuador: 'ec',
  Germany: 'de',
  'Curaçao': 'cw',
  Netherlands: 'nl',
  Japan: 'jp',
  Sweden: 'se',
  Tunisia: 'tn',
  Iran: 'ir',
  'New Zealand': 'nz',
  Spain: 'es',
  'Cape Verde': 'cv',
  Belgium: 'be',
  Egypt: 'eg',
  'Saudi Arabia': 'sa',
  Uruguay: 'uy',
  France: 'fr',
  Senegal: 'sn',
  Iraq: 'iq',
  Norway: 'no',
  Argentina: 'ar',
  Algeria: 'dz',
  Austria: 'at',
  Jordan: 'jo',
  Portugal: 'pt',
  'Democratic Republic of the Congo': 'cd',
  England: 'gb-eng',
  Croatia: 'hr',
  Uzbekistan: 'uz',
  Colombia: 'co',
  Ghana: 'gh',
  Panama: 'pa'
};

export function getFlagUrl(teamNameEn: string): string {
  const code = flagMap[teamNameEn];
  if (!code) return 'https://flagcdn.com/w80/un.png'; // Fallback
  return `https://flagcdn.com/w80/${code}.png`;
}
